/**
 * Client-side filter for the `references.html` API reference portal.
 *
 * The page renders every public symbol up-front; this module hides
 * non-matching rows via CSS `display: none` keyed on a single
 * `data-cdx-ref-hidden` attribute. `content-visibility: auto` (set in
 * CSS) lets the browser skip layout/paint for offscreen sections, so
 * even ~1500-item outputs stay responsive.
 *
 * State lives in URL query params so deep-links restore exactly. The
 * SPA router calls `refreshApiReference()` on `reinitPage()` — the
 * module idempotently re-binds when the user navigates into the
 * portal page from elsewhere.
 */

interface FilterState {
    query: string;
    bucket: string;
    kinds: Set<string>;
    stability: Set<string>;
}

const BOUND = new WeakSet<HTMLElement>();

const getPageRoot = (): HTMLElement | null =>
    document.querySelector<HTMLElement>('[data-cdx-page="api-reference"]');

const createEmptyState = (): FilterState => ({
    query: '',
    bucket: '',
    kinds: new Set<string>(),
    stability: new Set<string>()
});

const cloneState = (state: FilterState): FilterState => ({
    query: state.query,
    bucket: state.bucket,
    kinds: new Set(state.kinds),
    stability: new Set(state.stability)
});

const readKindsFromDom = (root: HTMLElement): Set<string> => {
    const out = new Set<string>();
    root.querySelectorAll<HTMLButtonElement>('[data-cdx-ref-kind-chip]').forEach(btn => {
        const k = btn.getAttribute('data-cdx-ref-kind-chip');
        if (k) {
            out.add(k);
        }
    });
    return out;
};

const readStabilityFromDom = (root: HTMLElement): Set<string> => {
    const out = new Set<string>();
    root.querySelectorAll<HTMLButtonElement>('[data-cdx-ref-stability-chip]').forEach(btn => {
        const s = btn.getAttribute('data-cdx-ref-stability-chip');
        if (s) {
            out.add(s);
        }
    });
    return out;
};

/** URL read accepts both the lowercase kind id (`component`) and the
 *  friendly label form (`Component`, `Type Alias`) — links shared by
 *  humans tend to be capitalised, links generated by the page itself
 *  are lowercase. Normalise on read; write lowercase ids. */
const normaliseToken = (
    raw: string,
    allowed: Set<string>,
    labels: Map<string, string>
): string | null => {
    const v = raw.trim();
    if (!v) {
        return null;
    }
    if (allowed.has(v)) {
        return v;
    }
    const lower = v.toLowerCase();
    if (allowed.has(lower)) {
        return lower;
    }
    const byLabel = labels.get(lower);
    if (byLabel) {
        return byLabel;
    }
    return null;
};

const readKindLabelMap = (root: HTMLElement): Map<string, string> => {
    const out = new Map<string, string>();
    root.querySelectorAll<HTMLButtonElement>('[data-cdx-ref-kind-chip]').forEach(btn => {
        const k = btn.getAttribute('data-cdx-ref-kind-chip');
        const label = btn.querySelector<HTMLElement>('.cdx-ref-kind-chip-label')?.textContent;
        if (k && label) {
            out.set(label.trim().toLowerCase(), k);
        }
    });
    return out;
};

const parseUrlState = (root: HTMLElement): FilterState => {
    const params = new URLSearchParams(window.location.search);
    const allKinds = readKindsFromDom(root);
    const allStability = readStabilityFromDom(root);
    const kindLabels = readKindLabelMap(root);
    const stabilityLabels = new Map<string, string>([
        ['stable', 'stable'],
        ['experimental', 'experimental'],
        ['deprecated', 'deprecated']
    ]);
    const state = createEmptyState();
    state.query = (params.get('q') ?? '').toLowerCase();
    state.bucket = params.get('bucket') ?? '';

    const kindParam = params.get('kind');
    if (kindParam) {
        for (const raw of kindParam.split(',')) {
            const k = normaliseToken(raw, allKinds, kindLabels);
            if (k) {
                state.kinds.add(k);
            }
        }
    } else {
        for (const k of allKinds) {
            state.kinds.add(k);
        }
    }

    const stabilityParam = params.get('stability');
    if (stabilityParam) {
        for (const raw of stabilityParam.split(',')) {
            const s = normaliseToken(raw, allStability, stabilityLabels);
            if (s) {
                state.stability.add(s);
            }
        }
    } else {
        for (const s of allStability) {
            state.stability.add(s);
        }
    }
    return state;
};

const writeUrlState = (root: HTMLElement, state: FilterState): void => {
    const allKinds = readKindsFromDom(root);
    const allStability = readStabilityFromDom(root);
    const params = new URLSearchParams(window.location.search);

    if (state.query) {
        params.set('q', state.query);
    } else {
        params.delete('q');
    }
    if (state.bucket) {
        params.set('bucket', state.bucket);
    } else {
        params.delete('bucket');
    }

    const kindArr = [...state.kinds];
    if (kindArr.length === 0 || kindArr.length === allKinds.size) {
        params.delete('kind');
    } else {
        params.set('kind', kindArr.join(','));
    }

    const stabilityArr = [...state.stability];
    if (stabilityArr.length === 0 || stabilityArr.length === allStability.size) {
        params.delete('stability');
    } else {
        params.set('stability', stabilityArr.join(','));
    }

    const search = params.toString();
    const next = `${window.location.pathname}${search ? `?${search}` : ''}${window.location.hash}`;
    window.history.replaceState(null, '', next);
};

const matchesItem = (
    el: HTMLElement,
    state: FilterState,
    activeKinds: Set<string>,
    activeStability: Set<string>
): boolean => {
    if (state.query) {
        const name = el.getAttribute('data-cdx-name') ?? '';
        if (!name.includes(state.query)) {
            return false;
        }
    }
    if (state.bucket) {
        const bucket = el.getAttribute('data-cdx-bucket') ?? '';
        if (bucket !== state.bucket) {
            return false;
        }
    }
    if (activeKinds.size > 0) {
        const kind = el.getAttribute('data-cdx-kind') ?? '';
        if (!activeKinds.has(kind)) {
            return false;
        }
    }
    if (activeStability.size > 0) {
        const stability = el.getAttribute('data-cdx-stability') ?? 'stable';
        if (!activeStability.has(stability)) {
            return false;
        }
    }
    return true;
};

const applyFilter = (root: HTMLElement, state: FilterState): void => {
    const items = root.querySelectorAll<HTMLElement>('.cdx-ref-item');
    const activeKinds = state.kinds;
    const activeStability = state.stability;

    const visibleByKind = new Map<string, number>();
    const visibleByStability = new Map<string, number>();

    items.forEach(el => {
        const hit = matchesItem(el, state, activeKinds, activeStability);
        if (hit) {
            el.removeAttribute('data-cdx-ref-hidden');
            const kind = el.getAttribute('data-cdx-kind') ?? '';
            visibleByKind.set(kind, (visibleByKind.get(kind) ?? 0) + 1);
            const stab = el.getAttribute('data-cdx-stability') ?? 'stable';
            visibleByStability.set(stab, (visibleByStability.get(stab) ?? 0) + 1);
        } else {
            el.setAttribute('data-cdx-ref-hidden', '1');
        }
    });

    let visibleSections = 0;
    root.querySelectorAll<HTMLElement>('.cdx-ref-bucket-section').forEach(section => {
        const remaining = section.querySelectorAll<HTMLElement>(
            '.cdx-ref-item:not([data-cdx-ref-hidden])'
        ).length;
        const countEl = section.querySelector<HTMLElement>('[data-cdx-bucket-count]');
        if (countEl) {
            countEl.textContent = String(remaining);
        }
        if (remaining === 0) {
            section.setAttribute('data-cdx-ref-hidden', '1');
        } else {
            section.removeAttribute('data-cdx-ref-hidden');
            visibleSections += 1;
        }
    });

    root.querySelectorAll<HTMLElement>('[data-cdx-ref-kind-count]').forEach(el => {
        const kind = el.getAttribute('data-cdx-ref-kind-count');
        if (kind) {
            el.textContent = String(visibleByKind.get(kind) ?? 0);
        }
    });
    root.querySelectorAll<HTMLElement>('[data-cdx-ref-stability-count]').forEach(el => {
        const stab = el.getAttribute('data-cdx-ref-stability-count');
        if (stab) {
            el.textContent = String(visibleByStability.get(stab) ?? 0);
        }
    });

    const empty = root.querySelector<HTMLElement>('[data-cdx-ref-empty]');
    if (empty) {
        empty.hidden = visibleSections > 0;
    }

    root.querySelectorAll<HTMLButtonElement>('[data-cdx-ref-kind-chip]').forEach(btn => {
        const kind = btn.getAttribute('data-cdx-ref-kind-chip') ?? '';
        const active = activeKinds.has(kind);
        btn.setAttribute('aria-pressed', active ? 'true' : 'false');
        btn.classList.toggle('cdx-ref-kind-chip--inactive', !active);
    });
    root.querySelectorAll<HTMLButtonElement>('[data-cdx-ref-stability-chip]').forEach(btn => {
        const stab = btn.getAttribute('data-cdx-ref-stability-chip') ?? '';
        const active = activeStability.has(stab);
        btn.setAttribute('aria-pressed', active ? 'true' : 'false');
        btn.classList.toggle('cdx-ref-stability-chip--inactive', !active);
    });

    const clearBtn = root.querySelector<HTMLButtonElement>('[data-cdx-ref-search-clear]');
    if (clearBtn) {
        clearBtn.hidden = state.query === '';
    }
};

const writeStateToInputs = (root: HTMLElement, state: FilterState): void => {
    const input = root.querySelector<HTMLInputElement>('[data-cdx-ref-search]');
    if (input && input.value !== state.query) {
        input.value = state.query;
    }
    const select = root.querySelector<HTMLSelectElement>('[data-cdx-ref-bucket-select]');
    if (select && select.value !== state.bucket) {
        select.value = state.bucket;
    }
};

const bind = (root: HTMLElement, state: FilterState): void => {
    const persist = (): void => {
        writeUrlState(root, state);
        applyFilter(root, state);
    };

    const input = root.querySelector<HTMLInputElement>('[data-cdx-ref-search]');
    input?.addEventListener('input', () => {
        state.query = (input.value ?? '').trim().toLowerCase();
        persist();
    });

    const select = root.querySelector<HTMLSelectElement>('[data-cdx-ref-bucket-select]');
    select?.addEventListener('change', () => {
        state.bucket = select.value;
        persist();
    });

    root.querySelectorAll<HTMLButtonElement>('[data-cdx-ref-kind-chip]').forEach(btn => {
        btn.addEventListener('click', () => {
            const k = btn.getAttribute('data-cdx-ref-kind-chip');
            if (!k) {
                return;
            }
            if (state.kinds.has(k)) {
                state.kinds.delete(k);
            } else {
                state.kinds.add(k);
            }
            persist();
        });
    });

    root.querySelectorAll<HTMLButtonElement>('[data-cdx-ref-stability-chip]').forEach(btn => {
        btn.addEventListener('click', () => {
            const s = btn.getAttribute('data-cdx-ref-stability-chip');
            if (!s) {
                return;
            }
            if (state.stability.has(s)) {
                state.stability.delete(s);
            } else {
                state.stability.add(s);
            }
            persist();
        });
    });

    const clearBtn = root.querySelector<HTMLButtonElement>('[data-cdx-ref-search-clear]');
    clearBtn?.addEventListener('click', () => {
        state.query = '';
        if (input) {
            input.value = '';
        }
        persist();
    });

    root.querySelectorAll<HTMLButtonElement>('[data-cdx-ref-reset]').forEach(btn => {
        btn.addEventListener('click', () => {
            const fresh = createEmptyState();
            for (const k of readKindsFromDom(root)) {
                fresh.kinds.add(k);
            }
            for (const s of readStabilityFromDom(root)) {
                fresh.stability.add(s);
            }
            Object.assign(state, cloneState(fresh));
            writeStateToInputs(root, state);
            persist();
        });
    });
};

const hydrate = (root: HTMLElement): void => {
    const state = parseUrlState(root);
    writeStateToInputs(root, state);
    bind(root, state);
    applyFilter(root, state);
};

export const initApiReference = (): void => {
    const root = getPageRoot();
    if (!root || BOUND.has(root)) {
        return;
    }
    BOUND.add(root);
    hydrate(root);
};

/** Re-bind after SPA navigation into the portal page. The previous root
 *  element is gone after `content-data` swap, so a fresh query + bind
 *  always wins; the WeakSet guards prevent double-binding within the
 *  same DOM node. */
export const refreshApiReference = (): void => {
    initApiReference();
};
